# Generated by Django 5.0.14 on 2026-06-17 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Credito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=150, verbose_name="Nombre / Entidad"),
                ),
                (
                    "entidad_tipo",
                    models.CharField(
                        choices=[
                            ("bancario", "Banco"),
                            ("cooperativa", "Cooperativa / Fondos de empleados"),
                            ("libranza", "Libranza"),
                            ("fintech", "Fintech / Digital (Rappi Pay, Addi, etc.)"),
                            ("familiar", "Familiar / Informal"),
                            ("otro", "Otro"),
                        ],
                        default="bancario",
                        max_length=15,
                        verbose_name="Tipo de entidad",
                    ),
                ),
                (
                    "capital",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Monto del crédito (COP)",
                    ),
                ),
                (
                    "tasa_ea",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=8,
                        verbose_name="Tasa EA (como decimal, ej: 0.25 para 25%)",
                    ),
                ),
                ("plazo_meses", models.IntegerField(verbose_name="Plazo (meses)")),
                (
                    "fecha_desembolso",
                    models.DateField(verbose_name="Fecha de desembolso"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crédito",
                "verbose_name_plural": "Créditos",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="CuotaCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField(verbose_name="Número de cuota")),
                ("fecha_pago", models.DateField(verbose_name="Fecha de pago")),
                (
                    "cuota_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Cuota total (COP)",
                    ),
                ),
                (
                    "interes",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Interés (COP)"
                    ),
                ),
                (
                    "capital_amortizado",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Capital amortizado (COP)",
                    ),
                ),
                (
                    "saldo_capital",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Saldo capital (COP)",
                    ),
                ),
                ("pagada", models.BooleanField(default=False, verbose_name="Pagada")),
                (
                    "fecha_pago_real",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de pago real"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "credito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuotas",
                        to="deudas.credito",
                        verbose_name="Crédito",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuota de Crédito",
                "verbose_name_plural": "Cuotas de Crédito",
                "ordering": ["credito", "numero"],
                "unique_together": {("credito", "numero")},
            },
        ),
    ]
