# Generated by Django 5.0.14 on 2026-06-17 23:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deudas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TarjetaCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=150, verbose_name="Nombre / Banco"),
                ),
                (
                    "banco",
                    models.CharField(max_length=150, verbose_name="Banco / Entidad"),
                ),
                (
                    "limite",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Límite (COP)"
                    ),
                ),
                (
                    "tasa_mensual",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=8,
                        verbose_name="Tasa mensual (decimal, ej: 0.0234 para 2.34%)",
                    ),
                ),
                (
                    "saldo_actual",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Saldo actual (COP)",
                    ),
                ),
                (
                    "fecha_corte",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="Día de corte (1–31)",
                    ),
                ),
                (
                    "fecha_limite_pago",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="Día límite de pago (1–31)",
                    ),
                ),
                (
                    "cuota_minima_pct",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.05"),
                        help_text="Porcentaje como decimal (ej: 0.05 = 5%%)",
                        max_digits=5,
                        verbose_name="% cuota mínima sobre saldo",
                    ),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarjeta de Crédito",
                "verbose_name_plural": "Tarjetas de Crédito",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="CompraTC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Monto (COP)"
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha de compra")),
                (
                    "descripcion",
                    models.CharField(max_length=250, verbose_name="Descripción"),
                ),
                (
                    "categoria",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Categoría"
                    ),
                ),
                (
                    "numero_cuotas",
                    models.IntegerField(
                        default=1,
                        help_text="1 = contado, >1 = diferido",
                        verbose_name="Número de cuotas",
                    ),
                ),
                (
                    "monto_cuota",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Monto por cuota (COP)",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "tarjeta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compras",
                        to="deudas.tarjetacredito",
                        verbose_name="Tarjeta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compra Tarjeta de Crédito",
                "verbose_name_plural": "Compras Tarjeta de Crédito",
                "ordering": ["-fecha"],
            },
        ),
    ]
