# Generated by Django 5.0.14 on 2026-06-17 04:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OtroIngreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("auxilio_transporte", "Auxilio de transporte"),
                            ("hora_extra_diurna", "Hora extra diurna (+25%)"),
                            ("hora_extra_nocturna", "Hora extra nocturna (+75%)"),
                            ("dominical_festivo", "Dominical y festivo (+75%)"),
                            ("comision", "Comisión"),
                            ("bonificacion", "Bonificación no salarial"),
                            ("honorarios", "Honorarios / Freelance"),
                            (
                                "ingreso_pasivo",
                                "Ingreso pasivo (arriendos, dividendos)",
                            ),
                            ("otro", "Otro"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de ingreso",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Monto (COP)"
                    ),
                ),
                ("mes", models.IntegerField(verbose_name="Mes")),
                ("anio", models.IntegerField(verbose_name="Año")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "recurrente",
                    models.BooleanField(
                        default=False, verbose_name="Recurrente mensual"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Otro Ingreso",
                "verbose_name_plural": "Otros Ingresos",
                "ordering": ["-anio", "-mes"],
            },
        ),
        migrations.CreateModel(
            name="PrestacionSocial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("prima_servicios", "Prima de Servicios"),
                            ("cesantias", "Cesantías"),
                            ("intereses_cesantias", "Intereses de Cesantías"),
                            ("vacaciones", "Vacaciones"),
                        ],
                        max_length=25,
                        verbose_name="Tipo de prestación",
                    ),
                ),
                (
                    "salario_base",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Salario base del cálculo (COP)",
                    ),
                ),
                (
                    "monto_proyectado",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Monto proyectado (COP)",
                    ),
                ),
                (
                    "meses_acumulados",
                    models.IntegerField(default=1, verbose_name="Meses acumulados"),
                ),
                ("anio", models.IntegerField(verbose_name="Año")),
                (
                    "fecha_pago_esperada",
                    models.DateField(verbose_name="Fecha de pago esperada"),
                ),
                ("pagada", models.BooleanField(default=False, verbose_name="Pagada")),
                (
                    "fecha_pago_real",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de pago real"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prestación Social",
                "verbose_name_plural": "Prestaciones Sociales",
                "ordering": ["fecha_pago_esperada"],
            },
        ),
        migrations.CreateModel(
            name="RegistroNomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salario_bruto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Salario bruto (COP)",
                    ),
                ),
                ("mes", models.IntegerField(verbose_name="Mes")),
                ("anio", models.IntegerField(verbose_name="Año")),
                (
                    "deduccion_salud",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Deducción salud (COP)",
                    ),
                ),
                (
                    "deduccion_pension",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Deducción pensión (COP)",
                    ),
                ),
                (
                    "deduccion_solidaridad",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Deducción fondo solidaridad (COP)",
                    ),
                ),
                (
                    "retencion_fuente",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Retención en la fuente (COP)",
                    ),
                ),
                (
                    "salario_neto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Salario neto (COP)",
                    ),
                ),
                (
                    "aplica_auxilio",
                    models.BooleanField(
                        default=False, verbose_name="Aplica auxilio de transporte"
                    ),
                ),
                (
                    "auxilio_transporte",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Auxilio de transporte (COP)",
                    ),
                ),
                (
                    "neto_con_auxilio",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Neto con auxilio (COP)",
                    ),
                ),
                (
                    "recurrente",
                    models.BooleanField(
                        default=False, verbose_name="Recurrente mensual"
                    ),
                ),
                (
                    "calculado_automaticamente",
                    models.BooleanField(
                        default=True, verbose_name="Calculado automáticamente"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Nómina",
                "verbose_name_plural": "Registros de Nómina",
                "ordering": ["-anio", "-mes"],
                "unique_together": {("usuario", "mes", "anio")},
            },
        ),
    ]
