# Generated by Django 5.0.14 on 2026-06-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingresos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otroingreso",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("auxilio_transporte", "Auxilio de transporte"),
                    ("hora_extra_diurna", "Hora extra diurna (+25%)"),
                    ("hora_extra_nocturna", "Hora extra nocturna (+75%)"),
                    ("dominical_festivo", "Dominical y festivo (+75%)"),
                    ("comision", "Comisión"),
                    ("bonificacion", "Bonificación no salarial"),
                    ("honorarios", "Honorarios / Freelance"),
                    ("ingreso_pasivo", "Ingreso pasivo (arriendos, dividendos)"),
                    ("prima_junio", "Prima de Servicios — Junio"),
                    ("prima_diciembre", "Prima de Servicios — Diciembre"),
                    ("otro", "Otro"),
                ],
                max_length=30,
                verbose_name="Tipo de ingreso",
            ),
        ),
    ]
