# Generated by Django 5.0.14 on 2026-06-17 15:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FondoEmergencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saldo_actual",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Saldo actual (COP)",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fondo de Emergencia",
                "verbose_name_plural": "Fondos de Emergencia",
            },
        ),
        migrations.CreateModel(
            name="AporteFondo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Monto (COP)"
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                ("mes", models.IntegerField(verbose_name="Mes")),
                ("anio", models.IntegerField(verbose_name="Año")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "fondo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aportes",
                        to="provisiones.fondoemergencia",
                        verbose_name="Fondo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aporte al Fondo",
                "verbose_name_plural": "Aportes al Fondo",
                "ordering": ["-fecha"],
            },
        ),
    ]
