# Generated by Django 5.0.14 on 2026-06-18 00:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provisiones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Provision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("concepto", models.CharField(max_length=200, verbose_name="Concepto")),
                (
                    "monto_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Monto total estimado (COP)",
                    ),
                ),
                ("fecha_pago", models.DateField(verbose_name="Fecha de pago")),
                (
                    "ahorro_acumulado",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Ahorro acumulado (COP)",
                    ),
                ),
                (
                    "ahorro_mensual_disponible",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Ahorro mensual disponible (COP)",
                    ),
                ),
                (
                    "es_sugerida",
                    models.BooleanField(default=False, verbose_name="Sugerida"),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provisión",
                "verbose_name_plural": "Provisiones",
                "ordering": ["fecha_pago"],
            },
        ),
        migrations.CreateModel(
            name="AporteProvision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Monto (COP)"
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "provision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aportes",
                        to="provisiones.provision",
                        verbose_name="Provisión",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aporte a Provisión",
                "verbose_name_plural": "Aportes a Provisiones",
                "ordering": ["-fecha"],
            },
        ),
    ]
