# Generated by Django 5.0.14 on 2026-06-17 03:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('anio', models.IntegerField(unique=True, verbose_name='Año vigente')),
                ('smlv', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='SMLV mensual (COP)')),
                ('auxilio_transporte', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Auxilio de transporte (COP)')),
                ('uvt', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='UVT (COP)')),
                ('umbral_retencion_uvt', models.DecimalField(decimal_places=2, default=Decimal('95'), max_digits=6, verbose_name='Umbral retención (UVT/mes)')),
                ('tasa_salud_empleado', models.DecimalField(decimal_places=4, default=Decimal('0.04'), max_digits=6, verbose_name='Tasa salud empleado (%)')),
                ('tasa_pension_empleado', models.DecimalField(decimal_places=4, default=Decimal('0.04'), max_digits=6, verbose_name='Tasa pensión empleado (%)')),
                ('umbral_solidaridad_smlv', models.DecimalField(decimal_places=1, default=Decimal('4'), max_digits=4, verbose_name='Umbral solidaridad (SMLV)')),
                ('tasa_solidaridad_4_16', models.DecimalField(decimal_places=4, default=Decimal('0.01'), max_digits=6, verbose_name='Solidaridad 4–16 SMLV (%)')),
                ('tasa_solidaridad_16_17', models.DecimalField(decimal_places=4, default=Decimal('0.012'), max_digits=6, verbose_name='Solidaridad 16–17 SMLV (%)')),
                ('tasa_solidaridad_17_18', models.DecimalField(decimal_places=4, default=Decimal('0.014'), max_digits=6, verbose_name='Solidaridad 17–18 SMLV (%)')),
                ('tasa_solidaridad_18_19', models.DecimalField(decimal_places=4, default=Decimal('0.016'), max_digits=6, verbose_name='Solidaridad 18–19 SMLV (%)')),
                ('tasa_solidaridad_19_20', models.DecimalField(decimal_places=4, default=Decimal('0.018'), max_digits=6, verbose_name='Solidaridad 19–20 SMLV (%)')),
                ('tasa_solidaridad_mas_20', models.DecimalField(decimal_places=4, default=Decimal('0.02'), max_digits=6, verbose_name='Solidaridad >20 SMLV (%)')),
                ('factor_prima_mensual', models.DecimalField(decimal_places=4, default=Decimal('0.0833'), max_digits=6, verbose_name='Factor prima mensual (%)')),
                ('factor_cesantias_mensual', models.DecimalField(decimal_places=4, default=Decimal('0.0833'), max_digits=6, verbose_name='Factor cesantías mensual (%)')),
                ('tasa_intereses_cesantias', models.DecimalField(decimal_places=4, default=Decimal('0.12'), max_digits=6, verbose_name='Tasa intereses cesantías anual (%)')),
                ('factor_vacaciones_mensual', models.DecimalField(decimal_places=4, default=Decimal('0.0417'), max_digits=6, verbose_name='Factor vacaciones mensual (%)')),
                ('cuota_minima_tc_pct', models.DecimalField(decimal_places=4, default=Decimal('0.05'), max_digits=5, verbose_name='Cuota mínima TC (% del saldo)')),
            ],
            options={
                'verbose_name': 'Configuración Fiscal',
                'verbose_name_plural': 'Configuraciones Fiscales',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('ciudad', models.CharField(default='Bogotá', max_length=100, verbose_name='Ciudad')),
                ('smlv_vigente', models.DecimalField(decimal_places=2, default=Decimal('1423500'), max_digits=14, verbose_name='SMLV vigente (COP)')),
                ('uvt_vigente', models.DecimalField(decimal_places=4, default=Decimal('49799'), max_digits=14, verbose_name='UVT vigente (COP)')),
                ('auxilio_transporte', models.DecimalField(decimal_places=2, default=Decimal('200000'), max_digits=14, verbose_name='Auxilio transporte (COP)')),
                ('meta_tasa_ahorro', models.DecimalField(decimal_places=2, default=Decimal('20.0'), max_digits=5, verbose_name='Meta tasa ahorro (%)')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('configuracion_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.configuracionfiscal', verbose_name='Configuración fiscal activa')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
