# Generated by Django 5.0.14 on 2026-06-18 02:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gastos", "0002_seed_categorias_sugeridas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Escenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            ("optimista", "Optimista"),
                            ("realista", "Realista"),
                            ("conservador", "Conservador"),
                        ],
                        max_length=20,
                        verbose_name="Nombre del escenario",
                    ),
                ),
                (
                    "factor_ingreso",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        max_digits=5,
                        verbose_name="Factor de ingreso (ej: 1.10 = +10%)",
                    ),
                ),
                (
                    "factor_gasto",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        max_digits=5,
                        verbose_name="Factor de gasto (ej: 0.95 = -5%)",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escenario",
                "verbose_name_plural": "Escenarios",
                "ordering": ["nombre"],
                "unique_together": {("usuario", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="ProyeccionGasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.IntegerField(verbose_name="Mes")),
                ("anio", models.IntegerField(verbose_name="Año")),
                (
                    "monto_proyectado",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Monto proyectado (COP)",
                    ),
                ),
                ("nota", models.TextField(blank=True, verbose_name="Nota")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gastos.categoria",
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "escenario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proyecciones.escenario",
                        verbose_name="Escenario",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyección de gasto",
                "verbose_name_plural": "Proyecciones de gastos",
                "ordering": ["anio", "mes"],
                "unique_together": {
                    ("usuario", "escenario", "mes", "anio", "categoria")
                },
            },
        ),
        migrations.CreateModel(
            name="ProyeccionIngreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.IntegerField(verbose_name="Mes")),
                ("anio", models.IntegerField(verbose_name="Año")),
                (
                    "fuente",
                    models.CharField(
                        choices=[("nomina", "Nómina"), ("otro", "Otro ingreso")],
                        default="nomina",
                        max_length=10,
                        verbose_name="Fuente de ingreso",
                    ),
                ),
                (
                    "monto_proyectado",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Monto proyectado (COP)",
                    ),
                ),
                ("nota", models.TextField(blank=True, verbose_name="Nota")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "escenario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proyecciones.escenario",
                        verbose_name="Escenario",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyección de ingreso",
                "verbose_name_plural": "Proyecciones de ingresos",
                "ordering": ["anio", "mes", "fuente"],
                "unique_together": {("usuario", "escenario", "mes", "anio", "fuente")},
            },
        ),
    ]
