# Generated by Django 5.0.14 on 2026-06-18 02:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorialIndicador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.IntegerField(verbose_name="Mes")),
                ("anio", models.IntegerField(verbose_name="Año")),
                (
                    "ratio_endeudamiento",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=8,
                        verbose_name="Ratio de endeudamiento (%)",
                    ),
                ),
                (
                    "semaforo_endeudamiento",
                    models.CharField(
                        default="verde",
                        max_length=10,
                        verbose_name="Semáforo endeudamiento",
                    ),
                ),
                (
                    "tasa_ahorro",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=8,
                        verbose_name="Tasa de ahorro (%)",
                    ),
                ),
                (
                    "semaforo_ahorro",
                    models.CharField(
                        default="verde", max_length=10, verbose_name="Semáforo ahorro"
                    ),
                ),
                (
                    "cobertura_emergencia",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=8,
                        verbose_name="Cobertura fondo emergencia (meses)",
                    ),
                ),
                (
                    "semaforo_emergencia",
                    models.CharField(
                        default="verde",
                        max_length=10,
                        verbose_name="Semáforo emergencia",
                    ),
                ),
                (
                    "presion_gastos_fijos",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=8,
                        verbose_name="Presión de gastos fijos (%)",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Indicador",
                "verbose_name_plural": "Historial de Indicadores",
                "ordering": ["-anio", "-mes"],
                "unique_together": {("usuario", "mes", "anio")},
            },
        ),
    ]
