# Generated by Django 5.0.14 on 2026-06-17 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "color",
                    models.CharField(
                        default="#2196F3", max_length=7, verbose_name="Color hex"
                    ),
                ),
                (
                    "icono",
                    models.CharField(blank=True, max_length=50, verbose_name="Icono"),
                ),
                (
                    "es_sugerida",
                    models.BooleanField(
                        default=False, verbose_name="Categoría sugerida"
                    ),
                ),
                (
                    "es_esencial",
                    models.BooleanField(
                        default=False, verbose_name="Esencial para fondo emergencia"
                    ),
                ),
                ("visible", models.BooleanField(default=True, verbose_name="Visible")),
                ("orden", models.IntegerField(default=0, verbose_name="Orden")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Rubro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "tipo",
                    models.CharField(
                        choices=[("fijo", "Fijo"), ("variable", "Variable")],
                        default="variable",
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "es_sugerida",
                    models.BooleanField(default=False, verbose_name="Rubro sugerido"),
                ),
                ("visible", models.BooleanField(default=True, verbose_name="Visible")),
                ("orden", models.IntegerField(default=0, verbose_name="Orden")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rubros",
                        to="gastos.categoria",
                        verbose_name="Categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rubro",
                "verbose_name_plural": "Rubros",
                "ordering": ["categoria", "orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Gasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Monto (COP)"
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("debito", "Débito"),
                            ("credito", "Crédito"),
                            ("transferencia", "Transferencia"),
                            ("nequi", "Nequi/Daviplata"),
                        ],
                        default="debito",
                        max_length=15,
                        verbose_name="Método de pago",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("fijo", "Fijo"), ("variable", "Variable")],
                        default="variable",
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "recurrente",
                    models.BooleanField(
                        default=False, verbose_name="Recurrente mensual"
                    ),
                ),
                ("mes", models.IntegerField(verbose_name="Mes")),
                ("anio", models.IntegerField(verbose_name="Año")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gastos.categoria",
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "rubro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gastos.rubro",
                        verbose_name="Rubro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto",
                "verbose_name_plural": "Gastos",
                "ordering": ["-fecha", "-creado_en"],
            },
        ),
    ]
